---
name: 刘思凡
surname: Sifan Liu
# position: ""
# address: ""
# phone: +1 202 790 3421
phone: 180 0169 8145
www: sifanliu.com
email: "sifan1121@gmail.com"
twitter: Sifan_Liu
github: fansi-sifan
date: "`r format(Sys.time(), '%B %Y')`"
# aboutme: 美国顶尖智库区域经济研究及数据分析经验，发表英文研究报告和综述30余篇，主要研究方向涉及数字经济时代产业动态和政策支持。熟练运用 R, Python 等工具进行数据分析、数据建模、和数据可视化。
aboutme: Experienced economic researcher at a leading think tank, with 30+ publications on sustainable infrastructure, economic impact of technology, startup ecosystems, and access to capital. Provided consultation for five regional economic development organizations on sectoral strategies. 
# Experienced analyst adept at collecting, analyzing, and interpreting large datasets, developing predictive models, and performing data management tasks.
geometry: "left=1.5cm,right=1.5cm,top=1cm,bottom=1.5cm"
output: vitae::awesomecv
headcolor: 333333
docname: résumé
# profilepic: "photo 2020.jpg"
#中文 zh, 英文 en
params:
  lang: en
  col: aiib
  # col:tech
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(magrittr) # For the pipe

data_location = "https://docs.google.com/spreadsheets/d/1z8us4_kADFyEZNinN_Ci_yrcyJwhcmXIRJPMXqcsBLo"  

googlesheets4::gs4_deauth()

get_data <- function(in_resume){
  in_resume <- sym(in_resume)
  
  googlesheets4::read_sheet(data_location, sheet = "entries", skip = 1, col_types = "c") %>% 
  # mutate(in_resume = as.logical(in_resume)) %>% 
  filter(!!in_resume!= "0") %>% 
  arrange(!!in_resume)
}

cv_data <- get_data(params$col)
```
 
```{r, results='asis'}
cat("#",ifelse(params$lang == "en", "Experience", "工作经历"), "\n")
```

```{r}
cv_data %>% 
  filter(language == params$lang) %>%
  filter(section == "positions") %>% 
  mutate(dates = paste0(start," - ", end)) %>% 
  detailed_entries(title, dates, institution, loc, description)
```


```{r, results='asis'}
cat("#",ifelse(params$lang == "en", "Education", "教育背景"), "\n")
```

```{r}
cv_data %>% 
  filter(language == params$lang) %>%
  filter(section == "education") %>% 
  mutate(dates = paste0(start," - ", end)) %>% 
  detailed_entries(title, dates, institution, loc, description)
```


```{r, results='asis'}
cat("#",ifelse(params$lang == "en", "Selected Publications", "学术成果"), "\n")
```

```{r}
# library(dplyr)
# tmp <- scholar::get_publications("SOfZqRsAAAAJ&") %>%
#   filter(grepl("economic|digitalization", title, ignore.case = T)) %>%
#   filter(!grepl("evidence", title, ignore.case = T)) %>% 
#   distinct(title, .keep_all = TRUE) %>%
#   transmute(bibtype = "Article", 
#             author = stringr::str_to_title(as.character(author)),
#             title = stringr::str_to_title(as.character(title)),
#             journaltitle = "Brookings Institution", year, key = row_number())
# 
# RefManageR::WriteBib(RefManageR::as.BibEntry(tmp), "Sliu.bib")

# bibliography_entries("Sliu.bib") 

cv_data %>%
  filter(grepl(params$lang, language)) %>%
  filter(section == "publications") %>%
  arrange(start) %>% 
  # mutate(dates = paste0(start," - ", end)) %>%
  brief_entries(what = description, when = start)

```

```{r, results='asis'}
cat("#",ifelse(params$lang == "en", "Skills", "专业技能"), "\n")
```

```{r}
cv_data %>% 
  filter(language == params$lang) %>%
  filter(section == "skills") %>%
  # mutate(dates = paste0(start," - ", end)) %>%
  brief_entries(what = description, when = start)
```

